In [6]:
# import necessary libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import r2_score
from scipy.stats import chi2_contingency
from statsmodels.stats.outliers_influence import variance_inflation_factor
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, precision_recall_fscore_support
import warnings
import os

In [7]:
#load datasets
a1 = pd.read_excel("E:\FraudPulse\Data\credit_risk\case_study1.xlsx")
a2 = pd.read_excel("E:\FraudPulse\Data\credit_risk\case_study2.xlsx")

In [8]:
#making copies of the datasets to work with
df1 = a1.copy()
df2 = a2.copy()

In [9]:
#checking shapes 
print("Shape of df1:", df1.shape)
print("Shape of df2:", df2.shape)

Shape of df1: (51336, 26)
Shape of df2: (51336, 62)

In [10]:
#checking info of the datasets
print("\nInfo of df1:")
print(df1.info())
print("\nInfo of df2:")
print(df2.info())

Info of df1:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51336 entries, 0 to 51335
Data columns (total 26 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   PROSPECTID            51336 non-null  int64
 1   Total_TL              51336 non-null  int64
 2   Tot_Closed_TL         51336 non-null  int64
 3   Tot_Active_TL         51336 non-null  int64
 4   Total_TL_opened_L6M   51336 non-null  int64
 5   Tot_TL_closed_L6M     51336 non-null  int64
 6   pct_tl_open_L6M       51336 non-null  float64
 7   pct_tl_closed_L6M     51336 non-null  float64
 8   pct_active_tl         51336 non-null  float64
 9   pct_closed_tl         51336 non-null  float64
 10  Total_TL_opened_L12M  51336 non-null  int64
 11  Tot_TL_closed_L12M    51336 non-null  int64
 12  pct_tl_open_L12M      51336 non-null  float64
 13  pct_tl_closed_L12M    51336 non-null  float64
 14  Tot_Missed_Pmnt       51336 non-null  int64
 15  Auto_TL               51336 non-null  int64
 16  CC_TL                 51336 non-null  int64
 17  Consumer_TL           51336 non-null  int64
 18  Gold_TL               51336 non-null  int64
 19  Home_TL               51336 non-null  int64
 20  PL_TL                 51336 non-null  int64
 21  Secured_TL            51336 non-null  int64
 22  Unsecured_TL          51336 non-null  int64
 23  Other_TL              51336 non-null  int64
 24  Age_Oldest_TL         51336 non-null  int64
 25  Age_Newest_TL         51336 non-null  int64
dtypes: float64(6), int64(20)
memory usage: 10.2 MB
None

Info of df2:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51336 entries, 0 to 51335
Data columns (total 62 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   PROSPECTID                    51336 non-null  int64
 1   time_since_recent_payment     51336 non-null  int64
 2   time_since_first_deliquency   51336 non-null  int64
 3   time_since_recent_deliquency  51336 non-null  int64
 4   num_times_delinquent          51336 non-null  int64
 5   max_delinquency_level         51336 non-null  int64
 6   max_recent_level_of_deliq     51336 non-null  int64
 7   num_deliq_6mts                51336 non-null  int64
 8   num_deliq_12mts               51336 non-null  int64
 9   num_deliq_6_12mts             51336 non-null  int64
 10  max_deliq_6mts                51336 non-null  int64
 11  max_deliq_12mts               51336 non-null  int64
 12  num_times_30p_dpd             51336 non-null  int64
 13  num_times_60p_dpd             51336 non-null  int64
 14  num_std                       51336 non-null  int64
 15  num_std_6mts                  51336 non-null  int64
 16  num_std_12mts                 51336 non-null  int64
 17  num_sub                       51336 non-null  int64
 18  num_sub_6mts                  51336 non-null  int64
 19  num_sub_12mts                 51336 non-null  int64
 20  num_dbt                       51336 non-null  int64
 21  num_dbt_6mts                  51336 non-null  int64
 22  num_dbt_12mts                 51336 non-null  int64
 23  num_lss                       51336 non-null  int64
 24  num_lss_6mts                  51336 non-null  int64
 25  num_lss_12mts                 51336 non-null  int64
 26  recent_level_of_deliq         51336 non-null  int64
 27  tot_enq                       51336 non-null  int64
 28  CC_enq                        51336 non-null  int64
 29  CC_enq_L6m                    51336 non-null  int64
 30  CC_enq_L12m                   51336 non-null  int64
 31  PL_enq                        51336 non-null  int64
 32  PL_enq_L6m                    51336 non-null  int64
 33  PL_enq_L12m                   51336 non-null  int64
 34  time_since_recent_enq         51336 non-null  int64
 35  enq_L12m                      51336 non-null  int64
 36  enq_L6m                       51336 non-null  int64
 37  enq_L3m                       51336 non-null  int64
 38  MARITALSTATUS                 51336 non-null  object
 39  EDUCATION                     51336 non-null  object
 40  AGE                           51336 non-null  int64
 41  GENDER                        51336 non-null  object
 42  NETMONTHLYINCOME              51336 non-null  int64
 43  Time_With_Curr_Empr           51336 non-null  int64
 44  pct_of_active_TLs_ever        51336 non-null  float64
 45  pct_opened_TLs_L6m_of_L12m    51336 non-null  float64
 46  pct_currentBal_all_TL         51336 non-null  float64
 47  CC_utilization                51336 non-null  float64
 48  CC_Flag                       51336 non-null  int64
 49  PL_utilization                51336 non-null  float64
 50  PL_Flag                       51336 non-null  int64
 51  pct_PL_enq_L6m_of_L12m        51336 non-null  float64
 52  pct_CC_enq_L6m_of_L12m        51336 non-null  float64
 53  pct_PL_enq_L6m_of_ever        51336 non-null  float64
 54  pct_CC_enq_L6m_of_ever        51336 non-null  float64
 55  max_unsec_exposure_inPct      51336 non-null  float64
 56  HL_Flag                       51336 non-null  int64
 57  GL_Flag                       51336 non-null  int64
 58  last_prod_enq2                51336 non-null  object
 59  first_prod_enq2               51336 non-null  object
 60  Credit_Score                  51336 non-null  int64
 61  Approved_Flag                 51336 non-null  object
dtypes: float64(10), int64(46), object(6)
memory usage: 24.3+ MB
None

In [11]:
#checking descriptive statistics
print("\nDescriptive statistics of df1:")
print(df1.describe())
print("\nDescriptive statistics of df2:")
print(df2.describe())

Descriptive statistics of df1:
         PROSPECTID      Total_TL  Tot_Closed_TL  Tot_Active_TL  \
count  51336.000000  51336.000000   51336.000000   51336.000000
mean   25668.500000      4.858598       2.770415       2.088184
std    14819.571046      7.177116       5.941680       2.290774
min        1.000000      1.000000       0.000000       0.000000
25%    12834.750000      1.000000       0.000000       1.000000
50%    25668.500000      2.000000       1.000000       1.000000
75%    38502.250000      5.000000       3.000000       3.000000
max    51336.000000    235.000000     216.000000      47.000000

       Total_TL_opened_L6M  Tot_TL_closed_L6M  pct_tl_open_L6M  \
count         51336.000000       51336.000000     51336.000000
mean              0.736754           0.428919         0.184574
std               1.296717           0.989972         0.297414
min               0.000000           0.000000         0.000000
25%               0.000000           0.000000         0.000000
50%               0.000000           0.000000         0.000000
75%               1.000000           1.000000         0.308000
max              27.000000          19.000000         1.000000

       pct_tl_closed_L6M  pct_active_tl  pct_closed_tl  ...         CC_TL  \
count       51336.000000   51336.000000   51336.000000  ...  51336.000000
mean            0.089095       0.577542       0.422458  ...      0.124981
std             0.205635       0.379867       0.379867  ...      0.505201
min             0.000000       0.000000       0.000000  ...      0.000000
25%             0.000000       0.250000       0.000000  ...      0.000000
50%             0.000000       0.556000       0.444000  ...      0.000000
75%             0.053000       1.000000       0.750000  ...      0.000000
max             1.000000       1.000000       1.000000  ...     27.000000

        Consumer_TL       Gold_TL       Home_TL         PL_TL    Secured_TL  \
count  51336.000000  51336.000000  51336.000000  51336.000000  51336.000000
mean       1.136084      1.561847      0.070146      0.282511      2.844904
std        2.227997      5.376434      0.340861      0.858168      6.187177
min        0.000000      0.000000      0.000000      0.000000      0.000000
25%        0.000000      0.000000      0.000000      0.000000      0.000000
50%        0.000000      0.000000      0.000000      0.000000      1.000000
75%        1.000000      1.000000      0.000000      0.000000      3.000000
max       41.000000    235.000000     10.000000     29.000000    235.000000

       Unsecured_TL      Other_TL  Age_Oldest_TL  Age_Newest_TL
count  51336.000000  51336.000000   51336.000000   51336.000000
mean       2.013694      1.089762     -32.575639     -62.149525
std        3.198322      2.417496    2791.869609    2790.818622
min        0.000000      0.000000  -99999.000000  -99999.000000
25%        0.000000      0.000000      14.000000       4.000000
50%        1.000000      0.000000      33.000000       8.000000
75%        2.000000      1.000000      64.000000      17.000000
max       55.000000     80.000000     392.000000     392.000000

[8 rows x 26 columns]

Descriptive statistics of df2:
         PROSPECTID  time_since_recent_payment  time_since_first_deliquency  \
count  51336.000000               51336.000000                 51336.000000
mean   25668.500000               -8129.961314                -70020.091320
std    14819.571046               27749.328514                 45823.312757
min        1.000000              -99999.000000                -99999.000000
25%    12834.750000                  46.000000                -99999.000000
50%    25668.500000                  70.000000                -99999.000000
75%    38502.250000                 161.000000                     8.000000
max    51336.000000                6065.000000                    35.000000

       time_since_recent_deliquency  num_times_delinquent  \
count                  51336.000000          51336.000000
mean                  -70022.375838              1.573749
std                    45819.820741              4.165012
min                   -99999.000000              0.000000
25%                   -99999.000000              0.000000
50%                   -99999.000000              0.000000
75%                        3.000000              1.000000
max                       35.000000             74.000000

       max_delinquency_level  max_recent_level_of_deliq  num_deliq_6mts  \
count           51336.000000               51336.000000    51336.000000
mean           -70003.987085                  13.521953        0.184977
std             45847.976100                  53.336976        0.710240
min            -99999.000000                   0.000000        0.000000
25%            -99999.000000                   0.000000        0.000000
50%            -99999.000000                   0.000000        0.000000
75%                15.000000                  10.000000        0.000000
max               900.000000                 900.000000       12.000000

       num_deliq_12mts  num_deliq_6_12mts  ...  PL_utilization       PL_Flag  \
count     51336.000000       51336.000000  ...    51336.000000  51336.000000
mean          0.480053           0.295076  ...   -86556.225194      0.167874
std           1.522210           1.027471  ...    34111.414750      0.373758
min           0.000000           0.000000  ...   -99999.000000      0.000000
25%           0.000000           0.000000  ...   -99999.000000      0.000000
50%           0.000000           0.000000  ...   -99999.000000      0.000000
75%           0.000000           0.000000  ...   -99999.000000      0.000000
max          28.000000          20.000000  ...        1.708000      1.000000

       pct_PL_enq_L6m_of_L12m  pct_CC_enq_L6m_of_L12m  pct_PL_enq_L6m_of_ever  \
count            51336.000000            51336.000000            51336.000000
mean                 0.190414                0.065182                0.170492
std                  0.376218                0.235706                0.350209
min                  0.000000                0.000000                0.000000
25%                  0.000000                0.000000                0.000000
50%                  0.000000                0.000000                0.000000
75%                  0.000000                0.000000                0.000000
max                  1.000000                1.000000                1.000000

       pct_CC_enq_L6m_of_ever  max_unsec_exposure_inPct       HL_Flag  \
count            51336.000000              51336.000000  51336.000000
mean                 0.056302             -45127.943635      0.271116
std                  0.213506              49795.784556      0.444540
min                  0.000000             -99999.000000      0.000000
25%                  0.000000             -99999.000000      0.000000
50%                  0.000000                  0.333000      0.000000
75%                  0.000000                  2.164250      1.000000
max                  1.000000             173800.000000      1.000000

            GL_Flag  Credit_Score
count  51336.000000  51336.000000
mean       0.052887    679.859222
std        0.223810     20.502764
min        0.000000    469.000000
25%        0.000000    669.000000
50%        0.000000    680.000000
75%        0.000000    691.000000
max        1.000000    811.000000

[8 rows x 56 columns]

In [12]:
#checking head of datasets
print("\nHead of df1:") 
print(df1.head())
print("\nHead of df2:")
print(df2.head())

Head of df1:
   PROSPECTID  Total_TL  Tot_Closed_TL  Tot_Active_TL  Total_TL_opened_L6M  \
0           1         5              4              1                    0
1           2         1              0              1                    0
2           3         8              0              8                    1
3           4         1              0              1                    1
4           5         3              2              1                    0

   Tot_TL_closed_L6M  pct_tl_open_L6M  pct_tl_closed_L6M  pct_active_tl  \
0                  0            0.000                0.0          0.200
1                  0            0.000                0.0          1.000
2                  0            0.125                0.0          1.000
3                  0            1.000                0.0          1.000
4                  0            0.000                0.0          0.333

   pct_closed_tl  ...  CC_TL  Consumer_TL  Gold_TL  Home_TL  PL_TL  \
0          0.800  ...      0            0        1        0      4
1          0.000  ...      0            1        0        0      0
2          0.000  ...      0            6        1        0      0
3          0.000  ...      0            0        0        0      0
4          0.667  ...      0            0        0        0      0

   Secured_TL  Unsecured_TL  Other_TL  Age_Oldest_TL  Age_Newest_TL
0           1             4         0             72             18
1           0             1         0              7              7
2           2             6         0             47              2
3           0             1         1              5              5
4           3             0         2            131             32

[5 rows x 26 columns]

Head of df2:
   PROSPECTID  time_since_recent_payment  time_since_first_deliquency  \
0           1                        549                           35
1           2                         47                       -99999
2           3                        302                           11
3           4                     -99999                       -99999
4           5                        583                       -99999

   time_since_recent_deliquency  num_times_delinquent  max_delinquency_level  \
0                            15                    11                     29
1                        -99999                     0                 -99999
2                             3                     9                     25
3                        -99999                     0                 -99999
4                        -99999                     0                 -99999

   max_recent_level_of_deliq  num_deliq_6mts  num_deliq_12mts  \
0                         29               0                0
1                          0               0                0
2                         25               1                9
3                          0               0                0
4                          0               0                0

   num_deliq_6_12mts  ...  pct_CC_enq_L6m_of_L12m  pct_PL_enq_L6m_of_ever  \
0                  0  ...                     0.0                     0.0
1                  0  ...                     0.0                     0.0
2                  8  ...                     0.0                     0.0
3                  0  ...                     0.0                     0.0
4                  0  ...                     0.0                     0.0

   pct_CC_enq_L6m_of_ever  max_unsec_exposure_inPct  HL_Flag  GL_Flag  \
0                     0.0                    13.333        1        0
1                     0.0                     0.860        0        0
2                     0.0                  5741.667        1        0
3                     0.0                     9.900        0        0
4                     0.0                -99999.000        0        0

   last_prod_enq2  first_prod_enq2  Credit_Score  Approved_Flag
0              PL               PL           696             P2
1    ConsumerLoan     ConsumerLoan           685             P2
2    ConsumerLoan           others           693             P2
3          others           others           673             P2
4              AL               AL           753             P1

[5 rows x 62 columns]

In [13]:
#remove nulls
df1 = df1.loc[df1['Age_Oldest_TL']!=-99999]

In [14]:
column_to_be_removed = []
for i in df2.columns:
    if df2.loc[df2[i] == -99999].shape[0] > 10000:
        column_to_be_removed.append(i)

print("Columns to be removed due to high number of nulls:", column_to_be_removed)

Columns to be removed due to high number of nulls: ['time_since_first_deliquency', 'time_since_recent_deliquency', 'max_delinquency_level', 'max_deliq_6mts', 'max_deliq_12mts', 'CC_utilization', 'PL_utilization', 'max_unsec_exposure_inPct']

In [15]:
df2=df2.drop(columns=column_to_be_removed, axis=1)

In [16]:
df2.shape

(51336, 54)

In [17]:
for i in df2.columns:
    df2 = df2.loc[df2[i] != -99999]

In [18]:
df2.shape

(42066, 54)

In [19]:
#checking null values
print("\nNull values in df1:")  
print(df1.isnull().sum())   
print("\nNull values in df2:")
print(df2.isnull().sum())

Null values in df1:
PROSPECTID              0
Total_TL                0
Tot_Closed_TL           0
Tot_Active_TL           0
Total_TL_opened_L6M     0
Tot_TL_closed_L6M       0
pct_tl_open_L6M         0
pct_tl_closed_L6M       0
pct_active_tl           0
pct_closed_tl           0
Total_TL_opened_L12M    0
Tot_TL_closed_L12M      0
pct_tl_open_L12M        0
pct_tl_closed_L12M      0
Tot_Missed_Pmnt         0
Auto_TL                 0
CC_TL                   0
Consumer_TL             0
Gold_TL                 0
Home_TL                 0
PL_TL                   0
Secured_TL              0
Unsecured_TL            0
Other_TL                0
Age_Oldest_TL           0
Age_Newest_TL           0
dtype: int64

Null values in df2:
PROSPECTID                    0
time_since_recent_payment     0
num_times_delinquent          0
max_recent_level_of_deliq     0
num_deliq_6mts                0
num_deliq_12mts               0
num_deliq_6_12mts             0
num_times_30p_dpd             0
num_times_60p_dpd             0
num_std                       0
num_std_6mts                  0
num_std_12mts                 0
num_sub                       0
num_sub_6mts                  0
num_sub_12mts                 0
num_dbt                       0
num_dbt_6mts                  0
num_dbt_12mts                 0
num_lss                       0
num_lss_6mts                  0
num_lss_12mts                 0
recent_level_of_deliq         0
tot_enq                       0
CC_enq                        0
CC_enq_L6m                    0
CC_enq_L12m                   0
PL_enq                        0
PL_enq_L6m                    0
PL_enq_L12m                   0
time_since_recent_enq         0
enq_L12m                      0
enq_L6m                       0
enq_L3m                       0
MARITALSTATUS                 0
EDUCATION                     0
AGE                           0
GENDER                        0
NETMONTHLYINCOME              0
Time_With_Curr_Empr           0
pct_of_active_TLs_ever        0
pct_opened_TLs_L6m_of_L12m    0
pct_currentBal_all_TL         0
CC_Flag                       0
PL_Flag                       0
pct_PL_enq_L6m_of_L12m        0
pct_CC_enq_L6m_of_L12m        0
pct_PL_enq_L6m_of_ever        0
pct_CC_enq_L6m_of_ever        0
HL_Flag                       0
GL_Flag                       0
last_prod_enq2                0
first_prod_enq2               0
Credit_Score                  0
Approved_Flag                 0
dtype: int64

In [20]:
#checking common coluns names
for i in list(df1.columns):
    if i not in df2.columns:
        print(i)

Total_TL
Tot_Closed_TL
Tot_Active_TL
Total_TL_opened_L6M
Tot_TL_closed_L6M
pct_tl_open_L6M
pct_tl_closed_L6M
pct_active_tl
pct_closed_tl
Total_TL_opened_L12M
Tot_TL_closed_L12M
pct_tl_open_L12M
pct_tl_closed_L12M
Tot_Missed_Pmnt
Auto_TL
CC_TL
Consumer_TL
Gold_TL
Home_TL
PL_TL
Secured_TL
Unsecured_TL
Other_TL
Age_Oldest_TL
Age_Newest_TL

In [21]:
#merge the two datasets, inner join so that no nulls are present 
df = pd.merge(df1, df2, how = 'inner', left_on=['PROSPECTID'], right_on=['PROSPECTID'])

In [22]:
print("\nShape of merged dataset:", df.shape)

Shape of merged dataset: (42064, 79)

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42064 entries, 0 to 42063
Data columns (total 79 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   PROSPECTID                  42064 non-null  int64
 1   Total_TL                    42064 non-null  int64
 2   Tot_Closed_TL               42064 non-null  int64
 3   Tot_Active_TL               42064 non-null  int64
 4   Total_TL_opened_L6M         42064 non-null  int64
 5   Tot_TL_closed_L6M           42064 non-null  int64
 6   pct_tl_open_L6M             42064 non-null  float64
 7   pct_tl_closed_L6M           42064 non-null  float64
 8   pct_active_tl               42064 non-null  float64
 9   pct_closed_tl               42064 non-null  float64
 10  Total_TL_opened_L12M        42064 non-null  int64
 11  Tot_TL_closed_L12M          42064 non-null  int64
 12  pct_tl_open_L12M            42064 non-null  float64
 13  pct_tl_closed_L12M          42064 non-null  float64
 14  Tot_Missed_Pmnt             42064 non-null  int64
 15  Auto_TL                     42064 non-null  int64
 16  CC_TL                       42064 non-null  int64
 17  Consumer_TL                 42064 non-null  int64
 18  Gold_TL                     42064 non-null  int64
 19  Home_TL                     42064 non-null  int64
 20  PL_TL                       42064 non-null  int64
 21  Secured_TL                  42064 non-null  int64
 22  Unsecured_TL                42064 non-null  int64
 23  Other_TL                    42064 non-null  int64
 24  Age_Oldest_TL               42064 non-null  int64
 25  Age_Newest_TL               42064 non-null  int64
 26  time_since_recent_payment   42064 non-null  int64
 27  num_times_delinquent        42064 non-null  int64
 28  max_recent_level_of_deliq   42064 non-null  int64
 29  num_deliq_6mts              42064 non-null  int64
 30  num_deliq_12mts             42064 non-null  int64
 31  num_deliq_6_12mts           42064 non-null  int64
 32  num_times_30p_dpd           42064 non-null  int64
 33  num_times_60p_dpd           42064 non-null  int64
 34  num_std                     42064 non-null  int64
 35  num_std_6mts                42064 non-null  int64
 36  num_std_12mts               42064 non-null  int64
 37  num_sub                     42064 non-null  int64
 38  num_sub_6mts                42064 non-null  int64
 39  num_sub_12mts               42064 non-null  int64
 40  num_dbt                     42064 non-null  int64
 41  num_dbt_6mts                42064 non-null  int64
 42  num_dbt_12mts               42064 non-null  int64
 43  num_lss                     42064 non-null  int64
 44  num_lss_6mts                42064 non-null  int64
 45  num_lss_12mts               42064 non-null  int64
 46  recent_level_of_deliq       42064 non-null  int64
 47  tot_enq                     42064 non-null  int64
 48  CC_enq                      42064 non-null  int64
 49  CC_enq_L6m                  42064 non-null  int64
 50  CC_enq_L12m                 42064 non-null  int64
 51  PL_enq                      42064 non-null  int64
 52  PL_enq_L6m                  42064 non-null  int64
 53  PL_enq_L12m                 42064 non-null  int64
 54  time_since_recent_enq       42064 non-null  int64
 55  enq_L12m                    42064 non-null  int64
 56  enq_L6m                     42064 non-null  int64
 57  enq_L3m                     42064 non-null  int64
 58  MARITALSTATUS               42064 non-null  object
 59  EDUCATION                   42064 non-null  object
 60  AGE                         42064 non-null  int64
 61  GENDER                      42064 non-null  object
 62  NETMONTHLYINCOME            42064 non-null  int64
 63  Time_With_Curr_Empr         42064 non-null  int64
 64  pct_of_active_TLs_ever      42064 non-null  float64
 65  pct_opened_TLs_L6m_of_L12m  42064 non-null  float64
 66  pct_currentBal_all_TL       42064 non-null  float64
 67  CC_Flag                     42064 non-null  int64
 68  PL_Flag                     42064 non-null  int64
 69  pct_PL_enq_L6m_of_L12m      42064 non-null  float64
 70  pct_CC_enq_L6m_of_L12m      42064 non-null  float64
 71  pct_PL_enq_L6m_of_ever      42064 non-null  float64
 72  pct_CC_enq_L6m_of_ever      42064 non-null  float64
 73  HL_Flag                     42064 non-null  int64
 74  GL_Flag                     42064 non-null  int64
 75  last_prod_enq2              42064 non-null  object
 76  first_prod_enq2             42064 non-null  object
 77  Credit_Score                42064 non-null  int64
 78  Approved_Flag               42064 non-null  object
dtypes: float64(13), int64(60), object(6)
memory usage: 25.4+ MB

In [24]:
df.head()

,PROSPECTID,Total_TL,Tot_Closed_TL,Tot_Active_TL,Total_TL_opened_L6M,Tot_TL_closed_L6M,pct_tl_open_L6M,pct_tl_closed_L6M,pct_active_tl,pct_closed_tl,...,pct_PL_enq_L6m_of_L12m,pct_CC_enq_L6m_of_L12m,pct_PL_enq_L6m_of_ever,pct_CC_enq_L6m_of_ever,HL_Flag,GL_Flag,last_prod_enq2,first_prod_enq2,Credit_Score,Approved_Flag
0,1,5,4,1,0,0,0.000,0.0,0.200,0.800,...,0.0,0.0,0.000,0.0,1,0,PL,PL,696,P2
1,2,1,0,1,0,0,0.000,0.0,1.000,0.000,...,0.0,0.0,0.000,0.0,0,0,ConsumerLoan,ConsumerLoan,685,P2
2,3,8,0,8,1,0,0.125,0.0,1.000,0.000,...,0.0,0.0,0.000,0.0,1,0,ConsumerLoan,others,693,P2
3,5,3,2,1,0,0,0.000,0.0,0.333,0.667,...,0.0,0.0,0.000,0.0,0,0,AL,AL,753,P1
4,6,6,5,1,0,0,0.000,0.0,0.167,0.833,...,1.0,0.0,0.429,0.0,1,0,ConsumerLoan,PL,668,P3

In [25]:
#checking for null value
df.isna().sum().sum()

0

In [26]:
#check how many columns are categorical
for i in df.columns:
    if df[i].dtype == 'object':
        print(i)

MARITALSTATUS
EDUCATION
GENDER
last_prod_enq2
first_prod_enq2
Approved_Flag

In [27]:
#values count in categorical columns
for i in df.columns:
    if df[i].dtype == 'object':
        print(f"\nValue counts for column '{i}':")
        print(df[i].value_counts())

Value counts for column 'MARITALSTATUS':
MARITALSTATUS
Married    30886
Single     11178
Name: count, dtype: int64

Value counts for column 'EDUCATION':
EDUCATION
GRADUATE          14140
12TH              11703
SSC                7241
UNDER GRADUATE     4572
OTHERS             2291
POST-GRADUATE      1898
PROFESSIONAL        219
Name: count, dtype: int64

Value counts for column 'GENDER':
GENDER
M    37345
F     4719
Name: count, dtype: int64

Value counts for column 'last_prod_enq2':
last_prod_enq2
ConsumerLoan    16480
others          13653
PL               7553
CC               2195
AL               1353
HL                830
Name: count, dtype: int64

Value counts for column 'first_prod_enq2':
first_prod_enq2
others          20640
ConsumerLoan    11075
PL               4431
AL               2641
CC               1988
HL               1289
Name: count, dtype: int64

Value counts for column 'Approved_Flag':
Approved_Flag
P2    25452
P3     6440
P4     5264
P1     4908
Name: count, dtype: int64

In [28]:
#chi square test for categorical variables
for i in ['MARITALSTATUS','EDUCATION','GENDER','last_prod_enq2','first_prod_enq2']:
    chi2,pval,_,_=chi2_contingency(pd.crosstab(df[i], df['Approved_Flag']))
    print(i,'---',pval)

MARITALSTATUS --- 3.578180861038862e-233
EDUCATION --- 2.6942265249737532e-30
GENDER --- 1.907936100186563e-05
last_prod_enq2 --- 0.0
first_prod_enq2 --- 7.84997610555419e-287

* since all the categorical features have pval <=0.05, we will accept all

In [29]:
#VIF for numerical variables
numerical_columns=[]
for i in df.columns:
    if df[i].dtype != 'object'and i not in ['PROSPECTID','Approved_Flag']:
        numerical_columns.append(i)

print("\nNumerical columns for VIF calculation:", numerical_columns)

Numerical columns for VIF calculation: ['Total_TL', 'Tot_Closed_TL', 'Tot_Active_TL', 'Total_TL_opened_L6M', 'Tot_TL_closed_L6M', 'pct_tl_open_L6M', 'pct_tl_closed_L6M', 'pct_active_tl', 'pct_closed_tl', 'Total_TL_opened_L12M', 'Tot_TL_closed_L12M', 'pct_tl_open_L12M', 'pct_tl_closed_L12M', 'Tot_Missed_Pmnt', 'Auto_TL', 'CC_TL', 'Consumer_TL', 'Gold_TL', 'Home_TL', 'PL_TL', 'Secured_TL', 'Unsecured_TL', 'Other_TL', 'Age_Oldest_TL', 'Age_Newest_TL', 'time_since_recent_payment', 'num_times_delinquent', 'max_recent_level_of_deliq', 'num_deliq_6mts', 'num_deliq_12mts', 'num_deliq_6_12mts', 'num_times_30p_dpd', 'num_times_60p_dpd', 'num_std', 'num_std_6mts', 'num_std_12mts', 'num_sub', 'num_sub_6mts', 'num_sub_12mts', 'num_dbt', 'num_dbt_6mts', 'num_dbt_12mts', 'num_lss', 'num_lss_6mts', 'num_lss_12mts', 'recent_level_of_deliq', 'tot_enq', 'CC_enq', 'CC_enq_L6m', 'CC_enq_L12m', 'PL_enq', 'PL_enq_L6m', 'PL_enq_L12m', 'time_since_recent_enq', 'enq_L12m', 'enq_L6m', 'enq_L3m', 'AGE', 'NETMONTHLYINCOME', 'Time_With_Curr_Empr', 'pct_of_active_TLs_ever', 'pct_opened_TLs_L6m_of_L12m', 'pct_currentBal_all_TL', 'CC_Flag', 'PL_Flag', 'pct_PL_enq_L6m_of_L12m', 'pct_CC_enq_L6m_of_L12m', 'pct_PL_enq_L6m_of_ever', 'pct_CC_enq_L6m_of_ever', 'HL_Flag', 'GL_Flag', 'Credit_Score']

In [30]:
#VIF Sequential Check
vif_data = df[numerical_columns]
total_columns = vif_data.shape[1]
columns_to_be_kept=[]
column_index = 0

for i in range(0,total_columns):
    vif_value = variance_inflation_factor(vif_data,column_index)
    print(column_index,'---',vif_value)

    if vif_value < 6:
        columns_to_be_kept.append(numerical_columns[i])
        column_index += 1
    else:
        vif_data = vif_data.drop(numerical_columns[i], axis=1)

c:\Users\Admin\anaconda3\envs\fp\lib\site-packages\statsmodels\stats\outliers_influence.py:197: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)

0 --- inf

c:\Users\Admin\anaconda3\envs\fp\lib\site-packages\statsmodels\stats\outliers_influence.py:197: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)

0 --- inf
0 --- 11.320180023967996
0 --- 8.363698035000336
0 --- 6.520647877790928
0 --- 5.149501618212625
1 --- 2.611111040579735

c:\Users\Admin\anaconda3\envs\fp\lib\site-packages\statsmodels\stats\outliers_influence.py:197: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)

2 --- inf
2 --- 1788.7926256209232
2 --- 8.601028256477228
2 --- 3.8328007921530785
3 --- 6.099653381646731
3 --- 5.5813520096427585
4 --- 1.9855843530987785

c:\Users\Admin\anaconda3\envs\fp\lib\site-packages\statsmodels\stats\outliers_influence.py:197: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)

5 --- inf
5 --- 4.809538302819343
6 --- 23.270628983464636
6 --- 30.595522588100053
6 --- 4.384346405965587
7 --- 3.064658415523423
8 --- 2.898639771299251
9 --- 4.377876915347322
10 --- 2.2078535836958433
11 --- 4.916914200506864
12 --- 5.214702030064725
13 --- 3.3861625024231476
14 --- 7.840583309478997
14 --- 5.255034641721438

c:\Users\Admin\anaconda3\envs\fp\lib\site-packages\statsmodels\stats\outliers_influence.py:197: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)

15 --- inf
15 --- 7.380634506427238
15 --- 1.4210050015175733
16 --- 8.083255010190316
16 --- 1.6241227524040112
17 --- 7.257811920140003
17 --- 15.59624383268298
17 --- 1.8258570471324314
18 --- 1.5080839450032664
19 --- 2.172088834824577
20 --- 2.623397553527229
21 --- 2.2959970812106176
22 --- 7.360578319196439
22 --- 2.160238777310255
23 --- 2.8686288267891467
24 --- 6.458218003637272
24 --- 2.8474118865638256
25 --- 4.753198156284083
26 --- 16.227354755948223
26 --- 6.424377256363872
26 --- 8.887080381808687
26 --- 2.3804746142952653
27 --- 8.609513476514548
27 --- 13.06755093547673
27 --- 3.500040056654654
28 --- 1.908795587481377
29 --- 17.006562234161628
29 --- 10.730485153719197
29 --- 2.3538497522950275
30 --- 22.104855915136433
30 --- 2.7971639638512906
31 --- 3.424171203217696
32 --- 10.175021454450912
32 --- 6.408710354561296
32 --- 1.0011511962625628
33 --- 3.069197305397274
34 --- 2.8091261600643724
35 --- 20.249538381980678
35 --- 15.864576541593774
35 --- 1.8331649740532172
36 --- 1.5680839909542046
37 --- 1.9307572353811682
38 --- 4.331265056645247
39 --- 9.390334396150173

In [31]:
print("\nColumns to be kept after VIF check:", columns_to_be_kept)
print("Number of columns to be kept:", len(columns_to_be_kept))

Columns to be kept after VIF check: ['pct_tl_open_L6M', 'pct_tl_closed_L6M', 'Tot_TL_closed_L12M', 'pct_tl_closed_L12M', 'Tot_Missed_Pmnt', 'CC_TL', 'Home_TL', 'PL_TL', 'Secured_TL', 'Unsecured_TL', 'Other_TL', 'Age_Oldest_TL', 'Age_Newest_TL', 'time_since_recent_payment', 'max_recent_level_of_deliq', 'num_deliq_6_12mts', 'num_times_60p_dpd', 'num_std_12mts', 'num_sub', 'num_sub_6mts', 'num_sub_12mts', 'num_dbt', 'num_dbt_12mts', 'num_lss', 'num_lss_12mts', 'recent_level_of_deliq', 'CC_enq_L12m', 'PL_enq_L12m', 'time_since_recent_enq', 'enq_L3m', 'NETMONTHLYINCOME', 'Time_With_Curr_Empr', 'pct_currentBal_all_TL', 'CC_Flag', 'PL_Flag', 'pct_PL_enq_L6m_of_ever', 'pct_CC_enq_L6m_of_ever', 'HL_Flag', 'GL_Flag']
Number of columns to be kept: 39

* Initially there were 72  numerical features out of which only 39 after VIF are selected

In [32]:
 #check anova for column_to_be_kept
from scipy.stats import f_oneway

column_to_be_kept_numerical = []

for i in columns_to_be_kept:
    a = list(df[i])
    b = list(df['Approved_Flag'])

    group_P1 = [value for value, group in zip(a, b) if group == 'P1']
    group_P2 = [value for value, group in zip(a, b) if group == 'P2']
    group_P3 = [value for value, group in zip(a, b) if group == 'P3']
    group_P4 = [value for value, group in zip(a, b) if group == 'P4']

    f_statistic, p_value = f_oneway(group_P1, group_P2, group_P3, group_P4)

    if p_value < 0.05:
        column_to_be_kept_numerical.append(i)

In [33]:
print("\nColumns to be kept after anova check:", column_to_be_kept_numerical)
print("Number of columns to be kept:", len(column_to_be_kept_numerical))

Columns to be kept after anova check: ['pct_tl_open_L6M', 'pct_tl_closed_L6M', 'Tot_TL_closed_L12M', 'pct_tl_closed_L12M', 'Tot_Missed_Pmnt', 'CC_TL', 'Home_TL', 'PL_TL', 'Secured_TL', 'Unsecured_TL', 'Other_TL', 'Age_Oldest_TL', 'Age_Newest_TL', 'time_since_recent_payment', 'max_recent_level_of_deliq', 'num_deliq_6_12mts', 'num_times_60p_dpd', 'num_std_12mts', 'num_sub', 'num_sub_6mts', 'num_sub_12mts', 'num_dbt', 'num_dbt_12mts', 'num_lss', 'recent_level_of_deliq', 'CC_enq_L12m', 'PL_enq_L12m', 'time_since_recent_enq', 'enq_L3m', 'NETMONTHLYINCOME', 'Time_With_Curr_Empr', 'CC_Flag', 'PL_Flag', 'pct_PL_enq_L6m_of_ever', 'pct_CC_enq_L6m_of_ever', 'HL_Flag', 'GL_Flag']
Number of columns to be kept: 37

In [34]:
df.shape

(42064, 79)

In [35]:
# listing all the final features
features = column_to_be_kept_numerical + ['MARITALSTATUS', 'EDUCATION', 'GENDER', 'last_prod_enq2', 'first_prod_enq2']
df = df[features + ['Approved_Flag']]

In [36]:
df.shape

(42064, 43)

In [37]:
df['MARITALSTATUS'].unique()    
df['EDUCATION'].unique()
df['GENDER'].unique()
df['last_prod_enq2'].unique()
df['first_prod_enq2'].unique()

array(['PL', 'ConsumerLoan', 'others', 'AL', 'HL', 'CC'], dtype=object)

In [38]:
# Ordinal feature -- EDUCATION
# SSC            : 1
# 12TH           : 2
# GRADUATE       : 3
# UNDER GRADUATE : 3
# POST-GRADUATE  : 4
# OTHERS         : 1
# PROFESSIONAL   : 3


# Others has to be verified by the business end user

In [39]:
df.loc[df['EDUCATION'] == 'SSC',['EDUCATION']]              = 1
df.loc[df['EDUCATION'] == '12TH',['EDUCATION']]             = 2
df.loc[df['EDUCATION'] == 'GRADUATE',['EDUCATION']]         = 3
df.loc[df['EDUCATION'] == 'UNDER GRADUATE',['EDUCATION']]   = 3
df.loc[df['EDUCATION'] == 'POST-GRADUATE',['EDUCATION']]    = 4
df.loc[df['EDUCATION'] == 'OTHERS',['EDUCATION']]           = 1
df.loc[df['EDUCATION'] == 'PROFESSIONAL',['EDUCATION']]     = 3

In [40]:
print(df['EDUCATION'].value_counts())
df['EDUCATION'] = df['EDUCATION'].astype(int)
df.info()

EDUCATION
3    18931
2    11703
1     9532
4     1898
Name: count, dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42064 entries, 0 to 42063
Data columns (total 43 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   pct_tl_open_L6M            42064 non-null  float64
 1   pct_tl_closed_L6M          42064 non-null  float64
 2   Tot_TL_closed_L12M         42064 non-null  int64
 3   pct_tl_closed_L12M         42064 non-null  float64
 4   Tot_Missed_Pmnt            42064 non-null  int64
 5   CC_TL                      42064 non-null  int64
 6   Home_TL                    42064 non-null  int64
 7   PL_TL                      42064 non-null  int64
 8   Secured_TL                 42064 non-null  int64
 9   Unsecured_TL               42064 non-null  int64
 10  Other_TL                   42064 non-null  int64
 11  Age_Oldest_TL              42064 non-null  int64
 12  Age_Newest_TL              42064 non-null  int64
 13  time_since_recent_payment  42064 non-null  int64
 14  max_recent_level_of_deliq  42064 non-null  int64
 15  num_deliq_6_12mts          42064 non-null  int64
 16  num_times_60p_dpd          42064 non-null  int64
 17  num_std_12mts              42064 non-null  int64
 18  num_sub                    42064 non-null  int64
 19  num_sub_6mts               42064 non-null  int64
 20  num_sub_12mts              42064 non-null  int64
 21  num_dbt                    42064 non-null  int64
 22  num_dbt_12mts              42064 non-null  int64
 23  num_lss                    42064 non-null  int64
 24  recent_level_of_deliq      42064 non-null  int64
 25  CC_enq_L12m                42064 non-null  int64
 26  PL_enq_L12m                42064 non-null  int64
 27  time_since_recent_enq      42064 non-null  int64
 28  enq_L3m                    42064 non-null  int64
 29  NETMONTHLYINCOME           42064 non-null  int64
 30  Time_With_Curr_Empr        42064 non-null  int64
 31  CC_Flag                    42064 non-null  int64
 32  PL_Flag                    42064 non-null  int64
 33  pct_PL_enq_L6m_of_ever     42064 non-null  float64
 34  pct_CC_enq_L6m_of_ever     42064 non-null  float64
 35  HL_Flag                    42064 non-null  int64
 36  GL_Flag                    42064 non-null  int64
 37  MARITALSTATUS              42064 non-null  object
 38  EDUCATION                  42064 non-null  int32
 39  GENDER                     42064 non-null  object
 40  last_prod_enq2             42064 non-null  object
 41  first_prod_enq2            42064 non-null  object
 42  Approved_Flag              42064 non-null  object
dtypes: float64(5), int32(1), int64(32), object(5)
memory usage: 13.6+ MB

In [41]:
df_encoded = pd.get_dummies(df, columns=['MARITALSTATUS','GENDER', 'last_prod_enq2' ,'first_prod_enq2'])

In [42]:
df_encoded.shape

(42064, 55)

In [43]:
df_encoded.head()

,pct_tl_open_L6M,pct_tl_closed_L6M,Tot_TL_closed_L12M,pct_tl_closed_L12M,Tot_Missed_Pmnt,CC_TL,Home_TL,PL_TL,Secured_TL,Unsecured_TL,...,last_prod_enq2_ConsumerLoan,last_prod_enq2_HL,last_prod_enq2_PL,last_prod_enq2_others,first_prod_enq2_AL,first_prod_enq2_CC,first_prod_enq2_ConsumerLoan,first_prod_enq2_HL,first_prod_enq2_PL,first_prod_enq2_others
0,0.000,0.0,0,0.000,0,0,0,4,1,4,...,False,False,True,False,False,False,False,False,True,False
1,0.000,0.0,0,0.000,0,0,0,0,0,1,...,True,False,False,False,False,False,True,False,False,False
2,0.125,0.0,0,0.000,1,0,0,0,2,6,...,True,False,False,False,False,False,False,False,False,True
3,0.000,0.0,0,0.000,0,0,0,0,3,0,...,False,False,False,False,True,False,False,False,False,False
4,0.000,0.0,1,0.167,0,0,0,0,6,0,...,True,False,False,False,False,False,False,False,True,False

In [44]:
df_encoded.info()
k = df_encoded.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42064 entries, 0 to 42063
Data columns (total 55 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   pct_tl_open_L6M               42064 non-null  float64
 1   pct_tl_closed_L6M             42064 non-null  float64
 2   Tot_TL_closed_L12M            42064 non-null  int64
 3   pct_tl_closed_L12M            42064 non-null  float64
 4   Tot_Missed_Pmnt               42064 non-null  int64
 5   CC_TL                         42064 non-null  int64
 6   Home_TL                       42064 non-null  int64
 7   PL_TL                         42064 non-null  int64
 8   Secured_TL                    42064 non-null  int64
 9   Unsecured_TL                  42064 non-null  int64
 10  Other_TL                      42064 non-null  int64
 11  Age_Oldest_TL                 42064 non-null  int64
 12  Age_Newest_TL                 42064 non-null  int64
 13  time_since_recent_payment     42064 non-null  int64
 14  max_recent_level_of_deliq     42064 non-null  int64
 15  num_deliq_6_12mts             42064 non-null  int64
 16  num_times_60p_dpd             42064 non-null  int64
 17  num_std_12mts                 42064 non-null  int64
 18  num_sub                       42064 non-null  int64
 19  num_sub_6mts                  42064 non-null  int64
 20  num_sub_12mts                 42064 non-null  int64
 21  num_dbt                       42064 non-null  int64
 22  num_dbt_12mts                 42064 non-null  int64
 23  num_lss                       42064 non-null  int64
 24  recent_level_of_deliq         42064 non-null  int64
 25  CC_enq_L12m                   42064 non-null  int64
 26  PL_enq_L12m                   42064 non-null  int64
 27  time_since_recent_enq         42064 non-null  int64
 28  enq_L3m                       42064 non-null  int64
 29  NETMONTHLYINCOME              42064 non-null  int64
 30  Time_With_Curr_Empr           42064 non-null  int64
 31  CC_Flag                       42064 non-null  int64
 32  PL_Flag                       42064 non-null  int64
 33  pct_PL_enq_L6m_of_ever        42064 non-null  float64
 34  pct_CC_enq_L6m_of_ever        42064 non-null  float64
 35  HL_Flag                       42064 non-null  int64
 36  GL_Flag                       42064 non-null  int64
 37  EDUCATION                     42064 non-null  int32
 38  Approved_Flag                 42064 non-null  object
 39  MARITALSTATUS_Married         42064 non-null  bool
 40  MARITALSTATUS_Single          42064 non-null  bool
 41  GENDER_F                      42064 non-null  bool
 42  GENDER_M                      42064 non-null  bool
 43  last_prod_enq2_AL             42064 non-null  bool
 44  last_prod_enq2_CC             42064 non-null  bool
 45  last_prod_enq2_ConsumerLoan   42064 non-null  bool
 46  last_prod_enq2_HL             42064 non-null  bool
 47  last_prod_enq2_PL             42064 non-null  bool
 48  last_prod_enq2_others         42064 non-null  bool
 49  first_prod_enq2_AL            42064 non-null  bool
 50  first_prod_enq2_CC            42064 non-null  bool
 51  first_prod_enq2_ConsumerLoan  42064 non-null  bool
 52  first_prod_enq2_HL            42064 non-null  bool
 53  first_prod_enq2_PL            42064 non-null  bool
 54  first_prod_enq2_others        42064 non-null  bool
dtypes: bool(16), float64(5), int32(1), int64(32), object(1)
memory usage: 13.0+ MB

In [45]:
df_encoded.shape

(42064, 55)

In [46]:
df_encoded.describe()

,pct_tl_open_L6M,pct_tl_closed_L6M,Tot_TL_closed_L12M,pct_tl_closed_L12M,Tot_Missed_Pmnt,CC_TL,Home_TL,PL_TL,Secured_TL,Unsecured_TL,...,enq_L3m,NETMONTHLYINCOME,Time_With_Curr_Empr,CC_Flag,PL_Flag,pct_PL_enq_L6m_of_ever,pct_CC_enq_L6m_of_ever,HL_Flag,GL_Flag,EDUCATION
count,42064.000000,42064.000000,42064.000000,42064.000000,42064.000000,42064.000000,42064.000000,42064.000000,42064.000000,42064.000000,...,42064.000000,4.206400e+04,42064.000000,42064.000000,42064.000000,42064.000000,42064.000000,42064.000000,42064.000000,42064.000000
mean,0.179032,0.097783,0.825504,0.160365,0.525746,0.145921,0.076241,0.328000,2.921334,2.341646,...,1.230458,2.692990e+04,110.345783,0.102962,0.193063,0.195497,0.064186,0.252235,0.056580,2.313689
std,0.278043,0.210957,1.537208,0.258831,1.106442,0.549314,0.358582,0.916368,6.379764,3.405397,...,2.069461,2.084300e+04,75.629967,0.303913,0.394707,0.367414,0.225989,0.434300,0.231042,0.871070
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,1.800000e+04,61.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,...,1.000000,2.400000e+04,92.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000
75%,0.333000,0.100000,1.000000,0.250000,1.000000,0.000000,0.000000,0.000000,3.000000,3.000000,...,2.000000,3.100000e+04,131.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,3.000000
max,1.000000,1.000000,33.000000,1.000000,34.000000,27.000000,10.000000,29.000000,235.000000,55.000000,...,42.000000,2.500000e+06,1020.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,4.000000

In [47]:
# Machine Learing model fitting

# Data processing

# 1. Random Forest

y = df_encoded['Approved_Flag']
x = df_encoded. drop ( ['Approved_Flag'], axis = 1 )

In [48]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [49]:
rf_classifier = RandomForestClassifier(n_estimators = 200, random_state=42)

In [50]:
rf_classifier.fit(x_train, y_train)

RandomForestClassifier(n_estimators=200, random_state=42)

In [51]:
y_pred = rf_classifier.predict(x_test)

In [52]:
accuracy = accuracy_score(y_test, y_pred)
print ()
print(f'Accuracy: {accuracy}')
print ()
precision, recall, f1_score, _ = precision_recall_fscore_support(y_test, y_pred)

Accuracy: 0.7636990372043266

In [53]:
for i, v in enumerate(['p1', 'p2', 'p3', 'p4']):
    print(f"Class {v}:")
    print(f"Precision: {precision[i]}")
    print(f"Recall: {recall[i]}")
    print(f"F1 Score: {f1_score[i]}")
    print()

Class p1:
Precision: 0.8370457209847597
Recall: 0.7041420118343196
F1 Score: 0.7648634172469202

Class p2:
Precision: 0.7957519116397621
Recall: 0.9282457879088206
F1 Score: 0.856907593778591

Class p3:
Precision: 0.4423380726698262
Recall: 0.21132075471698114
F1 Score: 0.28600612870275793

Class p4:
Precision: 0.7178502879078695
Recall: 0.7269193391642371
F1 Score: 0.7223563495895703

In [54]:
# 2. xgboost

import xgboost as xgb
from sklearn.preprocessing import LabelEncoder

xgb_classifier = xgb.XGBClassifier(objective='multi:softmax',  num_class=4)



y = df_encoded['Approved_Flag']
x = df_encoded. drop ( ['Approved_Flag'], axis = 1 )


label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)


x_train, x_test, y_train, y_test = train_test_split(x, y_encoded, test_size=0.2, random_state=42)




xgb_classifier.fit(x_train, y_train)
y_pred = xgb_classifier.predict(x_test)

accuracy = accuracy_score(y_test, y_pred)
print ()
print(f'Accuracy: {accuracy:.2f}')
print ()

precision, recall, f1_score, _ = precision_recall_fscore_support(y_test, y_pred)

for i, v in enumerate(['p1', 'p2', 'p3', 'p4']):
    print(f"Class {v}:")
    print(f"Precision: {precision[i]}")
    print(f"Recall: {recall[i]}")
    print(f"F1 Score: {f1_score[i]}")
    print()

Accuracy: 0.77

Class p1:
Precision: 0.8189655172413793
Recall: 0.7495069033530573
F1 Score: 0.7826982492276005

Class p2:
Precision: 0.8218123209169055
Recall: 0.909613478691774
F1 Score: 0.8634866873647568

Class p3:
Precision: 0.46557759626604434
Recall: 0.3011320754716981
F1 Score: 0.36571952337305225

Class p4:
Precision: 0.7279693486590039
Recall: 0.738581146744412
F1 Score: 0.733236854799807

In [55]:
# 3. Decision Tree
from sklearn.tree import DecisionTreeClassifier


y = df_encoded['Approved_Flag']
x = df_encoded. drop ( ['Approved_Flag'], axis = 1 )

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)


dt_model = DecisionTreeClassifier(max_depth=20, min_samples_split=10)
dt_model.fit(x_train, y_train)
y_pred = dt_model.predict(x_test)

accuracy = accuracy_score(y_test, y_pred)
print ()
print(f"Accuracy: {accuracy:.2f}")
print ()

precision, recall, f1_score, _ = precision_recall_fscore_support(y_test, y_pred)

for i, v in enumerate(['p1', 'p2', 'p3', 'p4']):
    print(f"Class {v}:")
    print(f"Precision: {precision[i]}")
    print(f"Recall: {recall[i]}")
    print(f"F1 Score: {f1_score[i]}")
    print()

Accuracy: 0.71

Class p1:
Precision: 0.7211350293542075
Recall: 0.7268244575936884
F1 Score: 0.7239685658153242

Class p2:
Precision: 0.8106163717674509
Recall: 0.8263627353815659
F1 Score: 0.8184138201806046

Class p3:
Precision: 0.3463375796178344
Recall: 0.3283018867924528
F1 Score: 0.33707865168539325

Class p4:
Precision: 0.6471774193548387
Recall: 0.6239067055393586
F1 Score: 0.6353290450272142

* Since Accuracy values of XgBoost is better, Now we will Further Finetune It which will include
* HP Tuning
* Feature Engineering-- Scalling, Feature Engg, Graphs
* see if we cn get better Results

In [56]:
#Hyper parameter Tuning for Xgboost
# Apply standard scaler 

from sklearn.preprocessing import StandardScaler

columns_to_be_scaled = ['Age_Oldest_TL','Age_Newest_TL','time_since_recent_payment',
'max_recent_level_of_deliq','recent_level_of_deliq',
'time_since_recent_enq','NETMONTHLYINCOME','Time_With_Curr_Empr']

for i in columns_to_be_scaled:
    column_data = df_encoded[i].values.reshape(-1, 1)
    scaler = StandardScaler()
    scaled_column = scaler.fit_transform(column_data)
    df_encoded[i] = scaled_column

In [57]:
import xgboost as xgb
from sklearn.preprocessing import LabelEncoder

xgb_classifier = xgb.XGBClassifier(objective='multi:softmax',  num_class=4)



y = df_encoded['Approved_Flag']
x = df_encoded. drop ( ['Approved_Flag'], axis = 1 )


label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)


x_train, x_test, y_train, y_test = train_test_split(x, y_encoded, test_size=0.2, random_state=42)




xgb_classifier.fit(x_train, y_train)
y_pred = xgb_classifier.predict(x_test)

accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy:.2f}')


precision, recall, f1_score, _ = precision_recall_fscore_support(y_test, y_pred)

for i, v in enumerate(['p1', 'p2', 'p3', 'p4']):
    print(f"Class {v}:")
    print(f"Precision: {precision[i]}")
    print(f"Recall: {recall[i]}")
    print(f"F1 Score: {f1_score[i]}")
    print()

Accuracy: 0.77
Class p1:
Precision: 0.8189655172413793
Recall: 0.7495069033530573
F1 Score: 0.7826982492276005

Class p2:
Precision: 0.8218123209169055
Recall: 0.909613478691774
F1 Score: 0.8634866873647568

Class p3:
Precision: 0.46557759626604434
Recall: 0.3011320754716981
F1 Score: 0.36571952337305225

Class p4:
Precision: 0.7279693486590039
Recall: 0.738581146744412
F1 Score: 0.733236854799807

* No improvement in metrices

In [58]:
# Hyperparameter tuning in xgboost
from sklearn.model_selection import GridSearchCV
x_train, x_test, y_train, y_test = train_test_split(x, y_encoded, test_size=0.2, random_state=42)

# Define the XGBClassifier with the initial set of hyperparameters
xgb_model = xgb.XGBClassifier(objective='multi:softmax', num_class=4)

# Define the parameter grid for hyperparameter tuning

param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [3, 5, 7],
    'learning_rate': [0.01, 0.1, 0.2],
}

grid_search = GridSearchCV(estimator=xgb_model, param_grid=param_grid, cv=3, scoring='accuracy', n_jobs=-1)
grid_search.fit(x_train, y_train)

# Print the best hyperparameters
print("Best Hyperparameters:", grid_search.best_params_)

# Evaluate the model with the best hyperparameters on the test set
best_model = grid_search.best_estimator_
accuracy = best_model.score(x_test, y_test)
print("Test Accuracy:", accuracy)

Best Hyperparameters: {'learning_rate': 0.2, 'max_depth': 3, 'n_estimators': 200}
Test Accuracy: 0.7812908593842862

* Best Hyperparameters: {'learning_rate': 0.2, 'max_depth': 3, 'n_estimators': 200}
* Based on risk appetite of the bank, you will suggest P1,P2,P3,P4 to the business end user

In [59]:
# # Hyperparameter tuning for xgboost (Used in the session)

# Define the hyperparameter grid
param_grid = {
   'colsample_bytree': [0.1, 0.3, 0.5, 0.7, 0.9],
   'learning_rate'   : [0.001, 0.01, 0.1, 1],
   'max_depth'       : [3, 5, 8, 10],
   'alpha'           : [1, 10, 100],
   'n_estimators'    : [10,50,100]
 }

index = 0

answers_grid = {
     'combination'       :[],
     'train_Accuracy'    :[],
     'test_Accuracy'     :[],
     'colsample_bytree'  :[],
     'learning_rate'     :[],
     'max_depth'         :[],
     'alpha'             :[],
     'n_estimators'      :[]

     }

In [60]:
# Loop through each combination of hyperparameters
for colsample_bytree in param_grid['colsample_bytree']:
    for learning_rate in param_grid['learning_rate']:
        for max_depth in param_grid['max_depth']:
            for alpha in param_grid['alpha']:
                for n_estimators in param_grid['n_estimators']:
                    index = index + 1
             
#               # Define and train the XGBoost model
                model = xgb.XGBClassifier(objective='multi:softmax',  
                                            num_class=4,
                                            colsample_bytree = colsample_bytree,                                        
                                            learning_rate = learning_rate,
                                            max_depth = max_depth,
                                            alpha = alpha,
                                            n_estimators = n_estimators)
               
       
                     
                y = df_encoded['Approved_Flag']
                x = df_encoded. drop ( ['Approved_Flag'], axis = 1 )

                label_encoder = LabelEncoder()
                y_encoded = label_encoder.fit_transform(y)

                x_train, x_test, y_train, y_test = train_test_split(x, y_encoded, test_size=0.2, random_state=42)


                model.fit(x_train, y_train)
  

       
#               # Predict on training and testing sets
                y_pred_train = model.predict(x_train)
                y_pred_test = model.predict(x_test)

                # Calculate train and test results
                train_accuracy = accuracy_score(y_train, y_pred_train)
                test_accuracy  = accuracy_score(y_test , y_pred_test)


                # Include into the lists
                answers_grid['combination'].append(index)
                answers_grid['train_Accuracy'].append(train_accuracy)
                answers_grid['test_Accuracy'].append(test_accuracy)
                answers_grid['colsample_bytree'].append(colsample_bytree)
                answers_grid['learning_rate'].append(learning_rate)
                answers_grid['max_depth'].append(max_depth)
                answers_grid['alpha'].append(alpha)
                answers_grid['n_estimators'].append(n_estimators)


                # Print results for this combination
                print(f"Combination {index}")
                print(f"colsample_bytree: {colsample_bytree}, learning_rate: {learning_rate}, max_depth: {max_depth}, alpha: {alpha}, n_estimators: {n_estimators}")
                print(f"Train Accuracy: {train_accuracy:.2f}")
                print(f"Test Accuracy : {test_accuracy :.2f}")
                print("-" * 30)

Combination 3
colsample_bytree: 0.1, learning_rate: 0.001, max_depth: 3, alpha: 1, n_estimators: 100
Train Accuracy: 0.61
Test Accuracy : 0.60
------------------------------
Combination 6
colsample_bytree: 0.1, learning_rate: 0.001, max_depth: 3, alpha: 10, n_estimators: 100
Train Accuracy: 0.61
Test Accuracy : 0.60
------------------------------
Combination 9
colsample_bytree: 0.1, learning_rate: 0.001, max_depth: 3, alpha: 100, n_estimators: 100
Train Accuracy: 0.61
Test Accuracy : 0.60
------------------------------
Combination 12
colsample_bytree: 0.1, learning_rate: 0.001, max_depth: 5, alpha: 1, n_estimators: 100
Train Accuracy: 0.61
Test Accuracy : 0.60
------------------------------
Combination 15
colsample_bytree: 0.1, learning_rate: 0.001, max_depth: 5, alpha: 10, n_estimators: 100
Train Accuracy: 0.61
Test Accuracy : 0.60
------------------------------
Combination 18
colsample_bytree: 0.1, learning_rate: 0.001, max_depth: 5, alpha: 100, n_estimators: 100
Train Accuracy: 0.61
Test Accuracy : 0.60
------------------------------
Combination 21
colsample_bytree: 0.1, learning_rate: 0.001, max_depth: 8, alpha: 1, n_estimators: 100
Train Accuracy: 0.61
Test Accuracy : 0.60
------------------------------
Combination 24
colsample_bytree: 0.1, learning_rate: 0.001, max_depth: 8, alpha: 10, n_estimators: 100
Train Accuracy: 0.61
Test Accuracy : 0.60
------------------------------
Combination 27
colsample_bytree: 0.1, learning_rate: 0.001, max_depth: 8, alpha: 100, n_estimators: 100
Train Accuracy: 0.61
Test Accuracy : 0.60
------------------------------
Combination 30
colsample_bytree: 0.1, learning_rate: 0.001, max_depth: 10, alpha: 1, n_estimators: 100
Train Accuracy: 0.61
Test Accuracy : 0.60
------------------------------
Combination 33
colsample_bytree: 0.1, learning_rate: 0.001, max_depth: 10, alpha: 10, n_estimators: 100
Train Accuracy: 0.61
Test Accuracy : 0.60
------------------------------
Combination 36
colsample_bytree: 0.1, learning_rate: 0.001, max_depth: 10, alpha: 100, n_estimators: 100
Train Accuracy: 0.61
Test Accuracy : 0.60
------------------------------
Combination 39
colsample_bytree: 0.1, learning_rate: 0.01, max_depth: 3, alpha: 1, n_estimators: 100
Train Accuracy: 0.61
Test Accuracy : 0.60
------------------------------
Combination 42
colsample_bytree: 0.1, learning_rate: 0.01, max_depth: 3, alpha: 10, n_estimators: 100
Train Accuracy: 0.61
Test Accuracy : 0.60
------------------------------
Combination 45
colsample_bytree: 0.1, learning_rate: 0.01, max_depth: 3, alpha: 100, n_estimators: 100
Train Accuracy: 0.61
Test Accuracy : 0.60
------------------------------
Combination 48
colsample_bytree: 0.1, learning_rate: 0.01, max_depth: 5, alpha: 1, n_estimators: 100
Train Accuracy: 0.61
Test Accuracy : 0.60
------------------------------
Combination 51
colsample_bytree: 0.1, learning_rate: 0.01, max_depth: 5, alpha: 10, n_estimators: 100
Train Accuracy: 0.61
Test Accuracy : 0.60
------------------------------
Combination 54
colsample_bytree: 0.1, learning_rate: 0.01, max_depth: 5, alpha: 100, n_estimators: 100
Train Accuracy: 0.61
Test Accuracy : 0.60
------------------------------
Combination 57
colsample_bytree: 0.1, learning_rate: 0.01, max_depth: 8, alpha: 1, n_estimators: 100
Train Accuracy: 0.61
Test Accuracy : 0.60
------------------------------
Combination 60
colsample_bytree: 0.1, learning_rate: 0.01, max_depth: 8, alpha: 10, n_estimators: 100
Train Accuracy: 0.61
Test Accuracy : 0.60
------------------------------
Combination 63
colsample_bytree: 0.1, learning_rate: 0.01, max_depth: 8, alpha: 100, n_estimators: 100
Train Accuracy: 0.61
Test Accuracy : 0.60
------------------------------
Combination 66
colsample_bytree: 0.1, learning_rate: 0.01, max_depth: 10, alpha: 1, n_estimators: 100
Train Accuracy: 0.61
Test Accuracy : 0.60
------------------------------
Combination 69
colsample_bytree: 0.1, learning_rate: 0.01, max_depth: 10, alpha: 10, n_estimators: 100
Train Accuracy: 0.61
Test Accuracy : 0.60
------------------------------
Combination 72
colsample_bytree: 0.1, learning_rate: 0.01, max_depth: 10, alpha: 100, n_estimators: 100
Train Accuracy: 0.61
Test Accuracy : 0.60
------------------------------
Combination 75
colsample_bytree: 0.1, learning_rate: 0.1, max_depth: 3, alpha: 1, n_estimators: 100
Train Accuracy: 0.73
Test Accuracy : 0.72
------------------------------
Combination 78
colsample_bytree: 0.1, learning_rate: 0.1, max_depth: 3, alpha: 10, n_estimators: 100
Train Accuracy: 0.72
Test Accuracy : 0.72
------------------------------
Combination 81
colsample_bytree: 0.1, learning_rate: 0.1, max_depth: 3, alpha: 100, n_estimators: 100
Train Accuracy: 0.71
Test Accuracy : 0.70
------------------------------
Combination 84
colsample_bytree: 0.1, learning_rate: 0.1, max_depth: 5, alpha: 1, n_estimators: 100
Train Accuracy: 0.74
Test Accuracy : 0.73
------------------------------
Combination 87
colsample_bytree: 0.1, learning_rate: 0.1, max_depth: 5, alpha: 10, n_estimators: 100
Train Accuracy: 0.73
Test Accuracy : 0.72
------------------------------
Combination 90
colsample_bytree: 0.1, learning_rate: 0.1, max_depth: 5, alpha: 100, n_estimators: 100
Train Accuracy: 0.71
Test Accuracy : 0.70
------------------------------
Combination 93
colsample_bytree: 0.1, learning_rate: 0.1, max_depth: 8, alpha: 1, n_estimators: 100
Train Accuracy: 0.77
Test Accuracy : 0.72
------------------------------
Combination 96
colsample_bytree: 0.1, learning_rate: 0.1, max_depth: 8, alpha: 10, n_estimators: 100
Train Accuracy: 0.74
Test Accuracy : 0.73
------------------------------
Combination 99
colsample_bytree: 0.1, learning_rate: 0.1, max_depth: 8, alpha: 100, n_estimators: 100
Train Accuracy: 0.71
Test Accuracy : 0.71
------------------------------
Combination 102
colsample_bytree: 0.1, learning_rate: 0.1, max_depth: 10, alpha: 1, n_estimators: 100
Train Accuracy: 0.79
Test Accuracy : 0.72
------------------------------
Combination 105
colsample_bytree: 0.1, learning_rate: 0.1, max_depth: 10, alpha: 10, n_estimators: 100
Train Accuracy: 0.74
Test Accuracy : 0.73
------------------------------
Combination 108
colsample_bytree: 0.1, learning_rate: 0.1, max_depth: 10, alpha: 100, n_estimators: 100
Train Accuracy: 0.71
Test Accuracy : 0.71
------------------------------
Combination 111
colsample_bytree: 0.1, learning_rate: 1, max_depth: 3, alpha: 1, n_estimators: 100
Train Accuracy: 0.80
Test Accuracy : 0.77
------------------------------
Combination 114
colsample_bytree: 0.1, learning_rate: 1, max_depth: 3, alpha: 10, n_estimators: 100
Train Accuracy: 0.79
Test Accuracy : 0.77
------------------------------
Combination 117
colsample_bytree: 0.1, learning_rate: 1, max_depth: 3, alpha: 100, n_estimators: 100
Train Accuracy: 0.76
Test Accuracy : 0.76
------------------------------
Combination 120
colsample_bytree: 0.1, learning_rate: 1, max_depth: 5, alpha: 1, n_estimators: 100
Train Accuracy: 0.86
Test Accuracy : 0.76
------------------------------
Combination 123
colsample_bytree: 0.1, learning_rate: 1, max_depth: 5, alpha: 10, n_estimators: 100
Train Accuracy: 0.81
Test Accuracy : 0.77
------------------------------
Combination 126
colsample_bytree: 0.1, learning_rate: 1, max_depth: 5, alpha: 100, n_estimators: 100
Train Accuracy: 0.76
Test Accuracy : 0.76
------------------------------
Combination 129
colsample_bytree: 0.1, learning_rate: 1, max_depth: 8, alpha: 1, n_estimators: 100
Train Accuracy: 0.94
Test Accuracy : 0.75
------------------------------
Combination 132
colsample_bytree: 0.1, learning_rate: 1, max_depth: 8, alpha: 10, n_estimators: 100
Train Accuracy: 0.82
Test Accuracy : 0.77
------------------------------
Combination 135
colsample_bytree: 0.1, learning_rate: 1, max_depth: 8, alpha: 100, n_estimators: 100
Train Accuracy: 0.76
Test Accuracy : 0.76
------------------------------
Combination 138
colsample_bytree: 0.1, learning_rate: 1, max_depth: 10, alpha: 1, n_estimators: 100
Train Accuracy: 0.97
Test Accuracy : 0.75
------------------------------
Combination 141
colsample_bytree: 0.1, learning_rate: 1, max_depth: 10, alpha: 10, n_estimators: 100
Train Accuracy: 0.83
Test Accuracy : 0.77
------------------------------
Combination 144
colsample_bytree: 0.1, learning_rate: 1, max_depth: 10, alpha: 100, n_estimators: 100
Train Accuracy: 0.76
Test Accuracy : 0.76
------------------------------
Combination 147
colsample_bytree: 0.3, learning_rate: 0.001, max_depth: 3, alpha: 1, n_estimators: 100
Train Accuracy: 0.61
Test Accuracy : 0.60
------------------------------
Combination 150
colsample_bytree: 0.3, learning_rate: 0.001, max_depth: 3, alpha: 10, n_estimators: 100
Train Accuracy: 0.61
Test Accuracy : 0.60
------------------------------
Combination 153
colsample_bytree: 0.3, learning_rate: 0.001, max_depth: 3, alpha: 100, n_estimators: 100
Train Accuracy: 0.61
Test Accuracy : 0.60
------------------------------
Combination 156
colsample_bytree: 0.3, learning_rate: 0.001, max_depth: 5, alpha: 1, n_estimators: 100
Train Accuracy: 0.61
Test Accuracy : 0.60
------------------------------
Combination 159
colsample_bytree: 0.3, learning_rate: 0.001, max_depth: 5, alpha: 10, n_estimators: 100
Train Accuracy: 0.61
Test Accuracy : 0.60
------------------------------
Combination 162
colsample_bytree: 0.3, learning_rate: 0.001, max_depth: 5, alpha: 100, n_estimators: 100
Train Accuracy: 0.61
Test Accuracy : 0.60
------------------------------
Combination 165
colsample_bytree: 0.3, learning_rate: 0.001, max_depth: 8, alpha: 1, n_estimators: 100
Train Accuracy: 0.61
Test Accuracy : 0.60
------------------------------
Combination 168
colsample_bytree: 0.3, learning_rate: 0.001, max_depth: 8, alpha: 10, n_estimators: 100
Train Accuracy: 0.61
Test Accuracy : 0.60
------------------------------
Combination 171
colsample_bytree: 0.3, learning_rate: 0.001, max_depth: 8, alpha: 100, n_estimators: 100
Train Accuracy: 0.61
Test Accuracy : 0.60
------------------------------
Combination 174
colsample_bytree: 0.3, learning_rate: 0.001, max_depth: 10, alpha: 1, n_estimators: 100
Train Accuracy: 0.61
Test Accuracy : 0.60
------------------------------
Combination 177
colsample_bytree: 0.3, learning_rate: 0.001, max_depth: 10, alpha: 10, n_estimators: 100
Train Accuracy: 0.61
Test Accuracy : 0.60
------------------------------
Combination 180
colsample_bytree: 0.3, learning_rate: 0.001, max_depth: 10, alpha: 100, n_estimators: 100
Train Accuracy: 0.61
Test Accuracy : 0.60
------------------------------
Combination 183
colsample_bytree: 0.3, learning_rate: 0.01, max_depth: 3, alpha: 1, n_estimators: 100
Train Accuracy: 0.62
Test Accuracy : 0.61
------------------------------
Combination 186
colsample_bytree: 0.3, learning_rate: 0.01, max_depth: 3, alpha: 10, n_estimators: 100
Train Accuracy: 0.62
Test Accuracy : 0.61
------------------------------
Combination 189
colsample_bytree: 0.3, learning_rate: 0.01, max_depth: 3, alpha: 100, n_estimators: 100
Train Accuracy: 0.61
Test Accuracy : 0.60
------------------------------
Combination 192
colsample_bytree: 0.3, learning_rate: 0.01, max_depth: 5, alpha: 1, n_estimators: 100
Train Accuracy: 0.63
Test Accuracy : 0.63
------------------------------
Combination 195
colsample_bytree: 0.3, learning_rate: 0.01, max_depth: 5, alpha: 10, n_estimators: 100
Train Accuracy: 0.63
Test Accuracy : 0.62
------------------------------
Combination 198
colsample_bytree: 0.3, learning_rate: 0.01, max_depth: 5, alpha: 100, n_estimators: 100
Train Accuracy: 0.61
Test Accuracy : 0.60
------------------------------
Combination 201
colsample_bytree: 0.3, learning_rate: 0.01, max_depth: 8, alpha: 1, n_estimators: 100
Train Accuracy: 0.64
Test Accuracy : 0.63
------------------------------
Combination 204
colsample_bytree: 0.3, learning_rate: 0.01, max_depth: 8, alpha: 10, n_estimators: 100
Train Accuracy: 0.63
Test Accuracy : 0.62
------------------------------
Combination 207
colsample_bytree: 0.3, learning_rate: 0.01, max_depth: 8, alpha: 100, n_estimators: 100
Train Accuracy: 0.61
Test Accuracy : 0.60
------------------------------
Combination 210
colsample_bytree: 0.3, learning_rate: 0.01, max_depth: 10, alpha: 1, n_estimators: 100
Train Accuracy: 0.65
Test Accuracy : 0.63
------------------------------
Combination 213
colsample_bytree: 0.3, learning_rate: 0.01, max_depth: 10, alpha: 10, n_estimators: 100
Train Accuracy: 0.63
Test Accuracy : 0.62
------------------------------
Combination 216
colsample_bytree: 0.3, learning_rate: 0.01, max_depth: 10, alpha: 100, n_estimators: 100
Train Accuracy: 0.61
Test Accuracy : 0.60
------------------------------
Combination 219
colsample_bytree: 0.3, learning_rate: 0.1, max_depth: 3, alpha: 1, n_estimators: 100
Train Accuracy: 0.77
Test Accuracy : 0.76
------------------------------
Combination 222
colsample_bytree: 0.3, learning_rate: 0.1, max_depth: 3, alpha: 10, n_estimators: 100
Train Accuracy: 0.77
Test Accuracy : 0.76
------------------------------
Combination 225
colsample_bytree: 0.3, learning_rate: 0.1, max_depth: 3, alpha: 100, n_estimators: 100
Train Accuracy: 0.75
Test Accuracy : 0.75
------------------------------
Combination 228
colsample_bytree: 0.3, learning_rate: 0.1, max_depth: 5, alpha: 1, n_estimators: 100
Train Accuracy: 0.80
Test Accuracy : 0.77
------------------------------
Combination 231
colsample_bytree: 0.3, learning_rate: 0.1, max_depth: 5, alpha: 10, n_estimators: 100
Train Accuracy: 0.79
Test Accuracy : 0.77
------------------------------
Combination 234
colsample_bytree: 0.3, learning_rate: 0.1, max_depth: 5, alpha: 100, n_estimators: 100
Train Accuracy: 0.76
Test Accuracy : 0.75
------------------------------
Combination 237
colsample_bytree: 0.3, learning_rate: 0.1, max_depth: 8, alpha: 1, n_estimators: 100
Train Accuracy: 0.87
Test Accuracy : 0.77
------------------------------
Combination 240
colsample_bytree: 0.3, learning_rate: 0.1, max_depth: 8, alpha: 10, n_estimators: 100
Train Accuracy: 0.80
Test Accuracy : 0.77
------------------------------
Combination 243
colsample_bytree: 0.3, learning_rate: 0.1, max_depth: 8, alpha: 100, n_estimators: 100
Train Accuracy: 0.76
Test Accuracy : 0.75
------------------------------
Combination 246
colsample_bytree: 0.3, learning_rate: 0.1, max_depth: 10, alpha: 1, n_estimators: 100
Train Accuracy: 0.92
Test Accuracy : 0.77
------------------------------
Combination 249
colsample_bytree: 0.3, learning_rate: 0.1, max_depth: 10, alpha: 10, n_estimators: 100
Train Accuracy: 0.81
Test Accuracy : 0.77
------------------------------
Combination 252
colsample_bytree: 0.3, learning_rate: 0.1, max_depth: 10, alpha: 100, n_estimators: 100
Train Accuracy: 0.76
Test Accuracy : 0.75
------------------------------
Combination 255
colsample_bytree: 0.3, learning_rate: 1, max_depth: 3, alpha: 1, n_estimators: 100
Train Accuracy: 0.82
Test Accuracy : 0.78
------------------------------
Combination 258
colsample_bytree: 0.3, learning_rate: 1, max_depth: 3, alpha: 10, n_estimators: 100
Train Accuracy: 0.81
Test Accuracy : 0.78
------------------------------
Combination 261
colsample_bytree: 0.3, learning_rate: 1, max_depth: 3, alpha: 100, n_estimators: 100
Train Accuracy: 0.77
Test Accuracy : 0.76
------------------------------
Combination 264
colsample_bytree: 0.3, learning_rate: 1, max_depth: 5, alpha: 1, n_estimators: 100
Train Accuracy: 0.91
Test Accuracy : 0.77
------------------------------
Combination 267
colsample_bytree: 0.3, learning_rate: 1, max_depth: 5, alpha: 10, n_estimators: 100
Train Accuracy: 0.85
Test Accuracy : 0.77
------------------------------
Combination 270
colsample_bytree: 0.3, learning_rate: 1, max_depth: 5, alpha: 100, n_estimators: 100
Train Accuracy: 0.78
Test Accuracy : 0.76
------------------------------
Combination 273
colsample_bytree: 0.3, learning_rate: 1, max_depth: 8, alpha: 1, n_estimators: 100
Train Accuracy: 1.00
Test Accuracy : 0.76
------------------------------
Combination 276
colsample_bytree: 0.3, learning_rate: 1, max_depth: 8, alpha: 10, n_estimators: 100
Train Accuracy: 0.90
Test Accuracy : 0.77
------------------------------
Combination 279
colsample_bytree: 0.3, learning_rate: 1, max_depth: 8, alpha: 100, n_estimators: 100
Train Accuracy: 0.78
Test Accuracy : 0.77
------------------------------
Combination 282
colsample_bytree: 0.3, learning_rate: 1, max_depth: 10, alpha: 1, n_estimators: 100
Train Accuracy: 1.00
Test Accuracy : 0.75
------------------------------
Combination 285
colsample_bytree: 0.3, learning_rate: 1, max_depth: 10, alpha: 10, n_estimators: 100
Train Accuracy: 0.92
Test Accuracy : 0.77
------------------------------
Combination 288
colsample_bytree: 0.3, learning_rate: 1, max_depth: 10, alpha: 100, n_estimators: 100
Train Accuracy: 0.78
Test Accuracy : 0.76
------------------------------
Combination 291
colsample_bytree: 0.5, learning_rate: 0.001, max_depth: 3, alpha: 1, n_estimators: 100
Train Accuracy: 0.61
Test Accuracy : 0.60
------------------------------
Combination 294
colsample_bytree: 0.5, learning_rate: 0.001, max_depth: 3, alpha: 10, n_estimators: 100
Train Accuracy: 0.61
Test Accuracy : 0.60
------------------------------
Combination 297
colsample_bytree: 0.5, learning_rate: 0.001, max_depth: 3, alpha: 100, n_estimators: 100
Train Accuracy: 0.61
Test Accuracy : 0.60
------------------------------
Combination 300
colsample_bytree: 0.5, learning_rate: 0.001, max_depth: 5, alpha: 1, n_estimators: 100
Train Accuracy: 0.61
Test Accuracy : 0.60
------------------------------
Combination 303
colsample_bytree: 0.5, learning_rate: 0.001, max_depth: 5, alpha: 10, n_estimators: 100
Train Accuracy: 0.61
Test Accuracy : 0.60
------------------------------
Combination 306
colsample_bytree: 0.5, learning_rate: 0.001, max_depth: 5, alpha: 100, n_estimators: 100
Train Accuracy: 0.61
Test Accuracy : 0.60
------------------------------
Combination 309
colsample_bytree: 0.5, learning_rate: 0.001, max_depth: 8, alpha: 1, n_estimators: 100
Train Accuracy: 0.61
Test Accuracy : 0.60
------------------------------
Combination 312
colsample_bytree: 0.5, learning_rate: 0.001, max_depth: 8, alpha: 10, n_estimators: 100
Train Accuracy: 0.61
Test Accuracy : 0.60
------------------------------
Combination 315
colsample_bytree: 0.5, learning_rate: 0.001, max_depth: 8, alpha: 100, n_estimators: 100
Train Accuracy: 0.61
Test Accuracy : 0.60
------------------------------
Combination 318
colsample_bytree: 0.5, learning_rate: 0.001, max_depth: 10, alpha: 1, n_estimators: 100
Train Accuracy: 0.61
Test Accuracy : 0.60
------------------------------
Combination 321
colsample_bytree: 0.5, learning_rate: 0.001, max_depth: 10, alpha: 10, n_estimators: 100
Train Accuracy: 0.61
Test Accuracy : 0.60
------------------------------
Combination 324
colsample_bytree: 0.5, learning_rate: 0.001, max_depth: 10, alpha: 100, n_estimators: 100
Train Accuracy: 0.61
Test Accuracy : 0.60
------------------------------
Combination 327
colsample_bytree: 0.5, learning_rate: 0.01, max_depth: 3, alpha: 1, n_estimators: 100
Train Accuracy: 0.65
Test Accuracy : 0.64
------------------------------
Combination 330
colsample_bytree: 0.5, learning_rate: 0.01, max_depth: 3, alpha: 10, n_estimators: 100
Train Accuracy: 0.65
Test Accuracy : 0.64
------------------------------
Combination 333
colsample_bytree: 0.5, learning_rate: 0.01, max_depth: 3, alpha: 100, n_estimators: 100
Train Accuracy: 0.63
Test Accuracy : 0.63
------------------------------
Combination 336
colsample_bytree: 0.5, learning_rate: 0.01, max_depth: 5, alpha: 1, n_estimators: 100
Train Accuracy: 0.67
Test Accuracy : 0.67
------------------------------
Combination 339
colsample_bytree: 0.5, learning_rate: 0.01, max_depth: 5, alpha: 10, n_estimators: 100
Train Accuracy: 0.66
Test Accuracy : 0.66
------------------------------
Combination 342
colsample_bytree: 0.5, learning_rate: 0.01, max_depth: 5, alpha: 100, n_estimators: 100
Train Accuracy: 0.64
Test Accuracy : 0.63
------------------------------

In [61]:
model1 = xgb.XGBClassifier(objective='multi:softmax',
                            num_class=4,
                            colsample_bytree = 0.9,                                        
                            learning_rate = 1,
                            max_depth = 3,
                            alpha = 10,
                            n_estimators = 100)

In [62]:
model1.fit(x_train, y_train)

XGBClassifier(alpha=10, base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.9, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=1, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=3,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=100,
              n_jobs=None, ...)

In [63]:
#predict for unseen dataset
import pandas as pd
a3 = pd.read_excel(r"E:\FraudPulse\Data\credit_risk\Unseen_Dataset.xlsx")

In [64]:
cols_in_df =list(df.columns)
cols_in_df.pop(42)

'Approved_Flag'

In [65]:
df_unseen = a3[cols_in_df]

df_unseen['MARITALSTATUS'].unique()
df_unseen['EDUCATION'].unique()
df_unseen['GENDER'].unique()
df_unseen['last_prod_enq2'].unique()
df_unseen['first_prod_enq2'].unique()

array(['PL', 'ConsumerLoan', 'others', 'AL', 'HL', 'CC'], dtype=object)

In [66]:
df_unseen.loc[df_unseen['EDUCATION'] == 'SSC',['EDUCATION']]              = 1
df_unseen.loc[df_unseen['EDUCATION'] == '12TH',['EDUCATION']]             = 2
df_unseen.loc[df_unseen['EDUCATION'] == 'GRADUATE',['EDUCATION']]         = 3
df_unseen.loc[df_unseen['EDUCATION'] == 'UNDER GRADUATE',['EDUCATION']]   = 3
df_unseen.loc[df_unseen['EDUCATION'] == 'POST-GRADUATE',['EDUCATION']]    = 4
df_unseen.loc[df_unseen['EDUCATION'] == 'OTHERS',['EDUCATION']]           = 1
df_unseen.loc[df_unseen['EDUCATION'] == 'PROFESSIONAL',['EDUCATION']]     = 3

In [67]:
df_unseen['EDUCATION'].value_counts()
df_unseen['EDUCATION'] = df_unseen['EDUCATION'].astype(int)
df_unseen.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 42 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   pct_tl_open_L6M            100 non-null    float64
 1   pct_tl_closed_L6M          100 non-null    float64
 2   Tot_TL_closed_L12M         100 non-null    int64
 3   pct_tl_closed_L12M         100 non-null    float64
 4   Tot_Missed_Pmnt            100 non-null    int64
 5   CC_TL                      100 non-null    int64
 6   Home_TL                    100 non-null    int64
 7   PL_TL                      100 non-null    int64
 8   Secured_TL                 100 non-null    int64
 9   Unsecured_TL               100 non-null    int64
 10  Other_TL                   100 non-null    int64
 11  Age_Oldest_TL              100 non-null    int64
 12  Age_Newest_TL              100 non-null    int64
 13  time_since_recent_payment  100 non-null    int64
 14  max_recent_level_of_deliq  100 non-null    int64
 15  num_deliq_6_12mts          100 non-null    int64
 16  num_times_60p_dpd          100 non-null    int64
 17  num_std_12mts              100 non-null    int64
 18  num_sub                    100 non-null    int64
 19  num_sub_6mts               100 non-null    int64
 20  num_sub_12mts              100 non-null    int64
 21  num_dbt                    100 non-null    int64
 22  num_dbt_12mts              100 non-null    int64
 23  num_lss                    100 non-null    int64
 24  recent_level_of_deliq      100 non-null    int64
 25  CC_enq_L12m                100 non-null    int64
 26  PL_enq_L12m                100 non-null    int64
 27  time_since_recent_enq      100 non-null    int64
 28  enq_L3m                    100 non-null    int64
 29  NETMONTHLYINCOME           100 non-null    int64
 30  Time_With_Curr_Empr        100 non-null    int64
 31  CC_Flag                    100 non-null    int64
 32  PL_Flag                    100 non-null    int64
 33  pct_PL_enq_L6m_of_ever     100 non-null    float64
 34  pct_CC_enq_L6m_of_ever     100 non-null    float64
 35  HL_Flag                    100 non-null    int64
 36  GL_Flag                    100 non-null    int64
 37  MARITALSTATUS              100 non-null    object
 38  EDUCATION                  100 non-null    int32
 39  GENDER                     100 non-null    object
 40  last_prod_enq2             100 non-null    object
 41  first_prod_enq2            100 non-null    object
dtypes: float64(5), int32(1), int64(32), object(4)
memory usage: 32.5+ KB

In [68]:
df_encoded_unseen= pd.get_dummies(df_unseen, columns=['MARITALSTATUS','GENDER', 'last_prod_enq2' ,'first_prod_enq2'])
df_encoded_unseen.info()
k = df_encoded_unseen.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 54 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   pct_tl_open_L6M               100 non-null    float64
 1   pct_tl_closed_L6M             100 non-null    float64
 2   Tot_TL_closed_L12M            100 non-null    int64
 3   pct_tl_closed_L12M            100 non-null    float64
 4   Tot_Missed_Pmnt               100 non-null    int64
 5   CC_TL                         100 non-null    int64
 6   Home_TL                       100 non-null    int64
 7   PL_TL                         100 non-null    int64
 8   Secured_TL                    100 non-null    int64
 9   Unsecured_TL                  100 non-null    int64
 10  Other_TL                      100 non-null    int64
 11  Age_Oldest_TL                 100 non-null    int64
 12  Age_Newest_TL                 100 non-null    int64
 13  time_since_recent_payment     100 non-null    int64
 14  max_recent_level_of_deliq     100 non-null    int64
 15  num_deliq_6_12mts             100 non-null    int64
 16  num_times_60p_dpd             100 non-null    int64
 17  num_std_12mts                 100 non-null    int64
 18  num_sub                       100 non-null    int64
 19  num_sub_6mts                  100 non-null    int64
 20  num_sub_12mts                 100 non-null    int64
 21  num_dbt                       100 non-null    int64
 22  num_dbt_12mts                 100 non-null    int64
 23  num_lss                       100 non-null    int64
 24  recent_level_of_deliq         100 non-null    int64
 25  CC_enq_L12m                   100 non-null    int64
 26  PL_enq_L12m                   100 non-null    int64
 27  time_since_recent_enq         100 non-null    int64
 28  enq_L3m                       100 non-null    int64
 29  NETMONTHLYINCOME              100 non-null    int64
 30  Time_With_Curr_Empr           100 non-null    int64
 31  CC_Flag                       100 non-null    int64
 32  PL_Flag                       100 non-null    int64
 33  pct_PL_enq_L6m_of_ever        100 non-null    float64
 34  pct_CC_enq_L6m_of_ever        100 non-null    float64
 35  HL_Flag                       100 non-null    int64
 36  GL_Flag                       100 non-null    int64
 37  EDUCATION                     100 non-null    int32
 38  MARITALSTATUS_Married         100 non-null    bool
 39  MARITALSTATUS_Single          100 non-null    bool
 40  GENDER_F                      100 non-null    bool
 41  GENDER_M                      100 non-null    bool
 42  last_prod_enq2_AL             100 non-null    bool
 43  last_prod_enq2_CC             100 non-null    bool
 44  last_prod_enq2_ConsumerLoan   100 non-null    bool
 45  last_prod_enq2_HL             100 non-null    bool
 46  last_prod_enq2_PL             100 non-null    bool
 47  last_prod_enq2_others         100 non-null    bool
 48  first_prod_enq2_AL            100 non-null    bool
 49  first_prod_enq2_CC            100 non-null    bool
 50  first_prod_enq2_ConsumerLoan  100 non-null    bool
 51  first_prod_enq2_HL            100 non-null    bool
 52  first_prod_enq2_PL            100 non-null    bool
 53  first_prod_enq2_others        100 non-null    bool
dtypes: bool(16), float64(5), int32(1), int64(32)
memory usage: 31.0 KB

In [74]:
for i in df_encoded.columns:
    if i not in list(df_encoded_unseen.columns):
        print(i)

Approved_Flag

In [69]:
model = xgb.XGBClassifier(objective='multi:softmax',
                            num_class=4,
                            colsample_bytree = 0.9,
                            learning_rate = 1,
                            max_depth = 3,
                            alpha = 10,
                            n_estimators = 100)

In [ ]:
model.fit(x_train, y_train)

XGBClassifier(alpha=10, base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.9, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=1, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=3,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=100,
              n_jobs=None, ...)

In [81]:
y_pred_unseen = model1.predict(df_encoded_unseen)

In [83]:
a3['Target_variable'] = y_pred_unseen
a3.to_excel(r"E:\\FraudPulse\\Data\\credit_risk\\Final_Predication.xlsx", index=False)

In [80]:
#print runtime
import time
start_time = time.time()
end_time = time.time()
elapsed_time = end_time - start_time
print(f"total run time of the program: {round(elapsed_time, 2)} seconds")

total run time of the program: 0.0 seconds